# economics

In [1]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import plotly.graph_objs as go
import plotly.express as px
import dash
from dash import html
from dash import dcc


df_economics_europe = pd.read_csv('df_economics_europe.csv', delimiter=',')

df_clustering = df_economics_europe.select_dtypes(include=['float64', 'int64'])

df_clustering = df_clustering.fillna(df_clustering.mean())

scaler = StandardScaler()
df_clustering_scaled = scaler.fit_transform(df_clustering)

# inertia = []
# for i in range(1, 11):
#     kmeans = KMeans(n_clusters=i, random_state=42)
#     kmeans.fit(df_clustering_scaled)
#     inertia.append(kmeans.inertia_)

# silhouette_scores = []
# for i in range(2, 11): # Silhouette score no se puede calcular para un solo cluster
#     kmeans = KMeans(n_clusters=i, random_state=42)
#     kmeans.fit(df_clustering_scaled)
#     score = silhouette_scores(df_clustering_scaled, kmeans.labels_)
#     silhouette_scores.append(score)c


kmeans_final = KMeans(n_clusters=4, random_state=42) # Cambia 3 por el número óptimo encontrado
kmeans_final.fit(df_clustering_scaled)
df_economics_europe['Cluster'] = kmeans_final.labels_



# plt.figure(figsize=(10, 6))
# plt.plot(range(1, 11), inertia, marker='o', linestyle='-', color='blue')
# plt.title('Método del Codo para Determinar el Número Óptimo de Clusters')
# plt.xlabel('Número de Clusters')
# plt.ylabel('Inercia')
# plt.grid(True)
# plt.show()


# plt.figure(figsize=(10, 6))
# plt.plot(range(2, 11), silhouette_scores, marker='o', linestyle='-', color='red')
# plt.title('Silhouette Score para Determinar el Número Óptimo de Clusters')
# plt.xlabel('Número de Clusters')
# plt.ylabel('Silhouette Score')
# plt.grid(True)
# plt.show()

In [2]:
moda_clusters = df_economics_europe.groupby('location')['Cluster'].agg(pd.Series.mode)

clusters_moda_dict = moda_clusters.to_dict()

for key, value in clusters_moda_dict.items():
    if isinstance(value, pd.Series):
        clusters_moda_dict[key] = value.iloc[0]

print(clusters_moda_dict)

{'Belgium': 2, 'Finland': 0, 'France': 0, 'Germany': 0, 'Hungary': 1, 'Italy': 3, 'Poland': 1, 'Romania': 1}

In [3]:
df_economics_europe['Cluster2'] = df_economics_europe['location'].map(clusters_moda_dict)

In [4]:
df_economics_europe

,location,education,date,GDP,gini,median_income,poorest_decile_threshold,richest_decile_threshold,trade,continent,Cluster,Cluster2
0,Belgium,6.425340,2017-01-01,1.620,0.273880,50.106460,25.195316,89.483215,165.325840,Europe,2,2
1,Belgium,6.381070,2018-01-01,1.793,0.272144,51.246574,26.038218,90.039635,166.494780,Europe,2,2
2,Belgium,6.333970,2019-01-01,2.262,0.272198,52.628468,27.698778,93.140700,164.176910,Europe,2,2
3,Belgium,6.812330,2020-01-01,-5.363,0.259583,53.040030,28.693867,91.954960,157.180730,Europe,2,2
4,Belgium,6.234233,2021-01-01,6.286,0.284037,39.714099,20.126681,70.713670,172.674450,Europe,2,2
5,Belgium,5.005333,2022-01-01,3.248,0.305781,44.786095,22.367731,84.200867,82.828154,Europe,0,2
6,Finland,6.363110,2017-01-01,3.192,0.273831,49.616215,28.033659,90.452280,75.053140,Europe,0,0
7,Finland,6.275580,2018-01-01,1.140,0.273298,50.388140,28.374876,91.765030,78.192170,Europe,0,0
8,Finland,6.416950,2019-01-01,1.224,0.277373,51.262200,28.351320,92.979256,79.605430,Europe,0,0
9,Finland,6.634940,2020-01-01,-2.355,0.270912,51.208990,29.307734,92.387900,71.634120,Europe,0,0
10,Finland,5.693809,2021-01-01,3.170,0.303654,38.295662,19.595188,71.516966,78.604590,Europe,0,0
11,Finland,5.522590,2022-01-01,1.605,0.308221,48.008721,22.987065,90.344385,103.800843,Europe,0,0
12,France,5.451600,2017-01-01,2.460,0.316321,49.441666,24.629000,94.996870,62.961845,Europe,0,0
13,France,5.407170,2018-01-01,1.818,0.323807,49.589756,24.751944,96.168710,64.437950,Europe,0,0
14,France,5.354430,2019-01-01,1.889,0.311996,48.568478,23.135792,90.886750,64.141470,Europe,0,0
15,France,5.677840,2020-01-01,-7.682,0.306615,50.136960,24.153225,92.650760,56.863823,Europe,0,0
16,France,5.245027,2021-01-01,6.370,0.332726,45.761436,20.860836,90.524783,60.839670,Europe,0,0
17,France,5.308559,2022-01-01,2.522,0.298572,50.694268,25.728431,94.561918,93.452041,Europe,0,0
18,Germany,4.871830,2017-01-01,2.680,0.318513,53.216515,25.144926,103.332990,87.237206,Europe,0,0
19,Germany,4.979330,2018-01-01,0.984,0.317907,54.922703,27.117777,108.009210,88.519875,Europe,0,0
20,Germany,5.116770,2019-01-01,1.071,0.317194,55.684288,26.758870,108.907110,87.686410,Europe,0,0
21,Germany,5.587590,2020-01-01,-3.829,0.297484,45.626998,23.680504,85.482089,80.398310,Europe,0,0
22,Germany,4.530964,2021-01-01,3.169,0.317897,39.102333,18.327078,76.644345,88.742775,Europe,3,0
23,Germany,5.522590,2022-01-01,1.804,0.308221,48.008721,22.987065,90.344385,103.800843,Europe,0,0
24,Hungary,4.614870,2017-01-01,4.272,0.305841,21.579445,10.446882,39.611034,165.228520,Europe,1,1
25,Hungary,4.623440,2018-01-01,5.362,0.296120,23.009550,11.254211,41.293766,163.261550,Europe,1,1
26,Hungary,4.224880,2019-01-01,4.864,0.299505,24.764103,13.261575,43.843765,160.782580,Europe,1,1
27,Hungary,4.155210,2020-01-01,-4.536,0.297131,26.530985,13.266785,49.587830,155.528380,Europe,1,1
28,Hungary,5.001584,2021-01-01,7.200,0.289509,34.417605,17.571352,61.474496,162.791850,Europe,1,1
29,Hungary,4.332032,2022-01-01,4.578,0.311750,19.921798,9.659271,38.132499,122.896818,Europe,1,1
30,Italy,4.044940,2017-01-01,1.668,0.359280,40.532337,15.814056,85.143616,58.604176,Europe,3,3
31,Italy,4.256140,2018-01-01,0.926,0.352226,40.674942,15.973390,85.427970,60.303550,Europe,3,3
32,Italy,4.095270,2019-01-01,0.483,0.345873,42.622936,17.259033,87.702420,59.878980,Europe,3,3
33,Italy,4.441950,2020-01-01,-8.979,0.352442,41.834790,17.427618,89.134155,55.286285,Europe,3,3
34,Italy,4.130886,2021-01-01,6.987,0.332726,45.761436,20.860836,90.524783,62.983124,Europe,3,3
35,Italy,4.953941,2022-01-01,3.722,0.309724,32.136172,15.842782,61.352185,98.426417,Europe,1,3
36,Poland,4.574650,2017-01-01,5.140,0.302966,16.996754,8.999455,33.843075,101.281220,Europe,1,1
37,Poland,4.605060,2018-01-01,5.945,0.311410,16.590326,8.660316,33.370914,103.450490,Europe,1,1
38,Poland,4.678810,2019-01-01,4.450,0.302395,17.241077,9.256153,34.283130,102.688710,Europe,1,1
39,Poland,4.852650,2020-01-01,-2.020,0.310374,32.287030,16.158514,63.682688,100.324210,Europe,3,1
40,Poland,4.941401,2021-01-01,6.935,0.318969,24.232113,11.762971,48.362908,112.445595,Europe,1,1
41,Poland,4.270966,2022-01-01,5.134,0.302479,19.720362,10.286342,37.326930,123.074490,Europe,1,1
42,Romania,3.118200,2017-01-01,8.213,0.360168,15.409707,4.781155,32.308210,87.156160,Europe,1,1
43,Romania,3.319180,2018-01-01,6.030,0.287829,12.660549,6.281528,23.890923,86.470670,Europe,1,1
44,Romania,3.566950,2019-01-01,3.844,0.348042,19.027610,6.332291,39.081493,84.503060,Europe,1,1
45,Romania,3.589260,2020-01-01,-3.692,0.345725,21.184145,6.883793,43.306770,78.059110,Europe,3,1
46,Romania,3.253052,2021-01-01,5.874,0.326349,31.199734,13.859754,61.504145,87.358390,Europe,3,1
47,Romania,4.543330,2022-01-01,4.743,0.301365,20.718186,10.643655,38.574954,138.648516,Europe,1,1

# Covid

In [5]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import plotly.graph_objs as go
import plotly.express as px
import dash
from dash import html
from dash import dcc


df_covid_HICP_europe = pd.read_csv('df_covid_HICP_europe.csv', delimiter=',')

df_clustering = df_covid_HICP_europe.select_dtypes(include=['float64', 'int64'])

df_clustering = df_clustering.fillna(df_clustering.mean())

scaler = StandardScaler()
df_clustering_scaled = scaler.fit_transform(df_clustering)

# inertia = []
# for i in range(1, 11):
#     kmeans = KMeans(n_clusters=i, random_state=42)
#     kmeans.fit(df_clustering_scaled)
#     inertia.append(kmeans.inertia_)

# silhouette_scores = []
# for i in range(2, 11): # Silhouette score no se puede calcular para un solo cluster
#     kmeans = KMeans(n_clusters=i, random_state=42)
#     kmeans.fit(df_clustering_scaled)
#     score = silhouette_scores(df_clustering_scaled, kmeans.labels_)
#     silhouette_scores.append(score)c


kmeans_final = KMeans(n_clusters=4, random_state=42) # Cambia 3 por el número óptimo encontrado
kmeans_final.fit(df_clustering_scaled)
df_covid_HICP_europe['Cluster'] = kmeans_final.labels_



# plt.figure(figsize=(10, 6))
# plt.plot(range(1, 11), inertia, marker='o', linestyle='-', color='blue')
# plt.title('Método del Codo para Determinar el Número Óptimo de Clusters')
# plt.xlabel('Número de Clusters')
# plt.ylabel('Inercia')
# plt.grid(True)
# plt.show()


# plt.figure(figsize=(10, 6))
# plt.plot(range(2, 11), silhouette_scores, marker='o', linestyle='-', color='red')
# plt.title('Silhouette Score para Determinar el Número Óptimo de Clusters')
# plt.xlabel('Número de Clusters')
# plt.ylabel('Silhouette Score')
# plt.grid(True)
# plt.show()

In [6]:
df_covid_HICP_europe

,date,HICP,location,total_deaths,stringency_index,total_cases_per_million,continent,Cluster
0,2020-01,0.111186,France,0.0,0.00,0.248,Europe,0
1,2020-02,0.111847,France,0.0,5.56,0.248,Europe,0
2,2020-03,0.113388,France,713.0,56.94,0.248,Europe,1
3,2020-04,0.112948,France,12062.0,87.96,0.248,Europe,1
4,2020-05,0.116691,France,17992.0,76.85,77.878,Europe,1
...,...,...,...,...,...,...,...,...
339,2023-01,2.131702,Italy,186158.0,0.00,429911.498,Europe,2
340,2023-02,1.937930,Italy,189155.0,0.00,435336.171,Europe,2
341,2023-03,1.568001,Italy,188974.0,0.00,434980.482,Europe,2
342,2023-04,1.539376,Italy,189627.0,0.00,436544.082,Europe,2
343,2023-05,1.488731,Italy,190122.0,0.00,437561.300,Europe,2

In [7]:
moda_clusters = df_covid_HICP_europe.groupby('location')['Cluster'].agg(pd.Series.mode)

clusters_moda_dict = moda_clusters.to_dict()

for key, value in clusters_moda_dict.items():
    if isinstance(value, pd.Series):
        clusters_moda_dict[key] = value.iloc[0]

print(clusters_moda_dict)

{'Belgium': 0, 'Finland': 1, 'France': 2, 'Germany': 1, 'Hungary': 0, 'Italy': 1, 'Poland': 3, 'Romania': 1}

In [8]:
df_covid_HICP_europe['Cluster2'] = df_covid_HICP_europe['location'].map(clusters_moda_dict)

In [9]:
df_covid_HICP_europe

,date,HICP,location,total_deaths,stringency_index,total_cases_per_million,continent,Cluster,Cluster2
0,2020-01,0.111186,France,0.0,0.00,0.248,Europe,0,2
1,2020-02,0.111847,France,0.0,5.56,0.248,Europe,0,2
2,2020-03,0.113388,France,713.0,56.94,0.248,Europe,1,2
3,2020-04,0.112948,France,12062.0,87.96,0.248,Europe,1,2
4,2020-05,0.116691,France,17992.0,76.85,77.878,Europe,1,2
...,...,...,...,...,...,...,...,...,...
339,2023-01,2.131702,Italy,186158.0,0.00,429911.498,Europe,2,1
340,2023-02,1.937930,Italy,189155.0,0.00,435336.171,Europe,2,1
341,2023-03,1.568001,Italy,188974.0,0.00,434980.482,Europe,2,1
342,2023-04,1.539376,Italy,189627.0,0.00,436544.082,Europe,2,1
343,2023-05,1.488731,Italy,190122.0,0.00,437561.300,Europe,2,1